
authentication:
  app_key: APP_KEY_APP_KEY_APP_KEY_APP_KEY_APP_KEY_APP_KEY_
  app_secret: APP_SECRET_APP_SECRET_APP_SECRET_APP_SECRET_
  uri:
    base: 'https://myOAUTHProviderServer.com'
    authorize: '/oauth/dialog'
    token: '/oauth2/token'
    verify: '/oauth2/verify-token'
    validate_ssl: false
  user_credentials:
    username: paulroon@gmail.com
    password: __myawesomepassword__

default:
  use_ssl: false
  base_url: http://requestb.in/12j0kq51
  default:
      cookie: 'XDEBUG_SESSION=PHPSTORM'
      query:
        XDEBUG_SESSION_START: PHPSTORM

endpoints:

    - name: Get 1 thing
      path: http://httpbin.org/html
      method: GET

    - name: Update Thingy
      path: /Thingies
      method: PUT
      body: |
            {
              "id":100,
              "name":"New Thingy"
            }

    - name: New Thingy
      path: /Thingies
      method: POST
      body: |
            {
              "name":"New Thingy"
            }

