
default:
  use_ssl: false
  base_url: httpbin.org
  default:
      cookie: 'XDEBUG_SESSION=PHPSTORM'
      query:
        XDEBUG_SESSION_START: PHPSTORM

endpoints:

    - name: Fetch Page
      path: /html
      method: GET

    - name: Update Thingy
      path: /put
      method: PUT
      body: |
            {
              "id":100,
              "name":"New Thingy"
            }

    - name: New Thingy
      path: /post
      method: POST
      body: |
            {
              "name":"New Thingy"
            }

